site:
  title: SITE_TITLE
  #url: https://docs.example.org
  #Add the appropriate URL - otherwise the main site title will redirect to all site files!
  #keys:
    #google_analytics: 
  start_page: ROOT::index.adoc
content:
  sources:
  #- url: https://github.com/USERNAME/REPO_NAME.git
  #uncomment and replace the url above to use a remote repository - see: https://docs.antora.org/antora/2.0/playbook/configure-content-sources/
  - url: ./
    branches: master
    #tags: 1.0
    #start_path:
#asciidoc:
#  attributes:
#    linkattrs: ''
#    toc: ~
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable  #Try using a full path - it's a bit safer this way

output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
runtime:
  cache_dir: ./.cache/antora
  fetch: true

#attributes/variables
asciidoc:
  attributes:
    revnumber: VERSION
    product: PROD_NAME
